### ISSUE TITLE
About authorized users adding subscription to a unauthorized channel in private chat can be successful but fail to subscribe within the channel.

### ISSUE THREAD

**Issue by vessel00** [Rongronggg9/RSS-to-Telegram-Bot#374]
In the case where MULTIUSER is set to 0, meaning non-multi-user mode where only a single authorized user but not an manager can use the bot, if this authorized single user uses the '/sub -10010000000 https://xxxx.xxx' command in private chat with the bot to add a subscription to a channel that the bot is in and  the bot is authorized as an admin, the subscription can be added successfully. However, if the user directly uses the '/sub' command to add the subscription within the channel, the bot will show an unauthorized error. Is this a bug?

**Comment by Rongronggg9** [comment]
This is intended. When a command is sent in a channel, there is no way to determine who is the sender. Thus, if you want to use the bot directly by channel messages, you will need to promote the channel itself to "user". That's why FAQ says `promote both the channel/group itself and at least one of its administrators to "User"`.

**Comment by vessel00** [comment]
OK. Thanks.
