### ISSUE TITLE
unsubsciribe not working

### ISSUE THREAD

**Issue by parduspanteri** [Rongronggg9/RSS-to-Telegram-Bot#408]
I can subscribe but can't unsubscribe. Unsubscribe doesn't work even though I've tried many times.  but unsub_all works.   What could be the problem?
![rss](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/assets/105588014/e8efb3bb-05dc-49f3-8aa5-f9dfa8774560)

**Comment by Rongronggg9** [comment]
`https://www.nitter.cz/bilinisterim/rss` permanently redirects to `https://nitter.cz/bilinisterim/rss`. The latter will be the one really gets subscribed.

Please copy the link from the subscription list, instead of just pasting the link you've used to subscribe.

And you can always use `/unsub` without any URL to select a subscription to be unsubscribed.
