### ISSUE TITLE
annoying "reply" when opening chat

### ISSUE THREAD

**Issue by ristein** [Rongronggg9/RSS-to-Telegram-Bot#413]
**Describe the bug**
When opening the chat there is this reply-banner above the typeing area that is espacially annoying on phone because there it would cause the keyboard to open.
Might be caused by an empty /sub command that does not stop opening reply banner even after being used once.

**To Reproduce**
1. Subscribe to something
2. Close Telegram
3. Open Telegram & Chat
4. See reply banner

**Expected behavior**
No reply banner should be open.

**Important log**
Nothing important there

**Comment by Rongronggg9** [comment]
This is rather a Telegram bug than a bug of RSStT. See also:
- #170

> Might be caused by an empty /sub command that does not stop opening reply banner even after being used once.

This has been fixed in 562ba8a8c014c4ee4f0eb9286cda10aaae661223 by deleting the prompt message after subscribing to feed(s).

What's more, 8d022bda8ff9b1ee26470ade3754d9d98cd65502 has limited the usage of `ForceReply` in groups so that an empty `/sub` in private chat should no longer open the reply banner.

If your bot is self-hosted, please upgrade it to the latest version.

<hr>

### However, manual operations must be done to make the pre-existing `ForceReply` banner disappear.

#### PC

1. Right-click the reply banner 
![](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/assets/15956627/8697eb24-8559-4b15-bc93-3d22ee81ab55)
2. Delete the prompt message 
![](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/assets/15956627/ba8e8477-07f7-4af1-b3af-52fcd120d8bc)
![](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/assets/15956627/a395f69d-3bdb-459b-84c6-e7b51b79be6e)

#### Android

1. Tap and hold the reply banner 
2. Delete the prompt message 

#### PC (alternative)

1. Click the reply banner 
2. "Show in chat"
![](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/assets/15956627/661cdb67-3bd4-4a92-baeb-8c55833c2922)
3. Delete the prompt message

**Comment by ristein** [comment]
> If your bot is self-hosted, please upgrade it to the latest version.

I am on latest, INFO:RSStT - RSS-to-Telegram-Bot (v2.5.0@master, build@2024-01-09T18:41:03+00:00) started!

**Comment by Rongronggg9** [comment]
> I am on latest, INFO:RSStT - RSS-to-Telegram-Bot (v2.5.0@master, build@2024-01-09T18:41:03+00:00) started!

> the pre-existing `ForceReply` banner
