### ISSUE TITLE
telethon.network.mtprotosender - Attempt 1 at connecting failed: TimeoutError:

### ISSUE THREAD

**Issue by Newfpv** [Rongronggg9/RSS-to-Telegram-Bot#429]
rsstt   | 2024-03-05-22:12:51:INFO:RSStT.env - Config folder: /app/config
rsstt   | 2024-03-05-22:12:52:INFO:RSStT.db - Successfully connected to the DB
rsstt   | 2024-03-05-22:13:02:WARNING:telethon.network.mtprotosender - Attempt 1 at connecting failed: TimeoutError:
rsstt   | 2024-03-05-22:13:13:WARNING:telethon.network.mtprotosender - Attempt 2 at connecting failed: TimeoutError:
rsstt   | 2024-03-05-22:13:24:WARNING:telethon.network.mtprotosender - Attempt 3 at connecting failed: TimeoutError:

**Comment by Rongronggg9** [comment]
Check your network connection

**Comment by Newfpv** [comment]
Network connection is good

**Comment by Newfpv** [comment]
newfpv@CodeBreakers:~/rsstt$ curl -v https://149.154.167.51
*   Trying 149.154.167.51:443...
* connect to 149.154.167.51 port 443 failed: Connection timed out
* Failed to connect to 149.154.167.51 port 443 after 129503 ms: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to 149.154.167.51 port 443 after 129503 ms: Connection timed out

How to fix this?

**Comment by Rongronggg9** [comment]
So it is proven that:

> probably out of order somewhere invisible

Use a proxy, migrate to another ISP, or simply deploy RSStT on a VPS without network issues. 

That's not an RSStT bug, so I can't help you further.

**Comment by Newfpv** [comment]
Another telegram bot is working for me. And it works perfectly

**Comment by Rongronggg9** [comment]
That you can connect to a Telegram DC doesn't mean that you can connect to another. Other Telegram bots, if using HTTP bot API, connect to Telegram DC4. RSStT uses MTProto API, which ties to the DC your account belonged to (in your case, DC2). It is impossible to invoke MTProto API from a foreign DC, that's why RSStT didn't work.

In short, you are facing a network issue preventing RSStT from connecting to Telegram DC2. That's not an RSStT bug, so I can't help you further.
