### ISSUE TITLE
Getting 403 on certain feeds that work on desktop.

### ISSUE THREAD

**Issue by SpyderZ** [Rongronggg9/RSS-to-Telegram-Bot#51]
Hello,

This feed, which works in the browser, will not work in the script.

```
Failed to subscribe
https://www.rt.com/rss/ (ERROR: HTTP status code error (403 Forbidden))
```

When I curl the feed URL, I see that I'm getting a security screen of code for DDoS-Guard that has a five-second delay before being forwarded to the RSS Feed data. Once a cookie is set, the next visit is not bothered by DDoS-Guard.

What do you recommend in this situation where a delay, cookie, and redirect need to be followed to obtain a feed?

**Comment by Rongronggg9** [comment]
Hi, as far as I know, this limitation was added after Russia had invaded Ukraine. So the best way is to wait for the war to end and RT no longer faces DDoS.

It is really hard for a bot consisting of no browsers to pass the browser integrity check. So the bot will easily face a DDoS Guard check. Manually setting cookies will not help much since the cookies are only valid for a short time and the browser integrity check persists.

Alternatively, you may set up a reverse proxy to RT with automatic DDoS protection check solution.

To be honest, an RSS feed with strict DDoS protection is just junk that never wants any users to subscribe to it. A lot of RSS readers can never pass the check.

**Comment by SpyderZ** [comment]
Thanks for the reply and suggestion about a reverse proxy, I was able to get it working with https://rss.app/

Both sides must be heard so people can make their minds up to where the truth is in this ocean of propaganda we find ourselves. It was the fake news that got us into previous wars.

I've tested a lot of Telegram-RSS reader scripts over last week; your script is the absolute best I've seen. Really great work, you are a master! 🏆

**Comment by Rongronggg9** [comment]
Yup, we should always listen to both sides. There are never any authorities or news media who deserve our full trust. The more sides we've listened to, the harder we deceived.

Thanks for your praise of my bot! I will keep trying my best to make it more perfect.
