### ISSUE TITLE
Some posts missing links

### ISSUE THREAD

**Issue by soredake** [Rongronggg9/RSS-to-Telegram-Bot#75]
**Describe the bug**
I've monitoring [this subreddit](https://www.reddit.com/r/FreeGameFindings/.rss) with your bot, and some posts are missing links (`[link]` and `[comments]`)

How i see it in bot:
![изображение](https://user-images.githubusercontent.com/5204968/168413726-6e01c847-b414-41ce-914f-3520f1c0bd1f.png)

How i see it with [feed preview firefox addon](https://addons.mozilla.org/ru/firefox/addon/feed-preview/):
![изображение](https://user-images.githubusercontent.com/5204968/168413743-7a125e1e-f8e2-4cd9-9f41-599a7421ea5f.png)

**To Reproduce**
1. Subscribe to `https://www.reddit.com/r/FreeGameFindings/.rss` in bot
2. Wait for posts
3. Most posts will be missing `[link]` and `[comments]` links

**Expected behavior**
Have the `[link]` and `[comments]` links, as expected

**Important log**
You may execute `docker logs [container name]` to get log.
Choose that is important and paste it here.

**Comment by Rongronggg9** [comment]
Thanks for your report. I have investigated the issue. It is caused by the weird format of the feed.

![](https://user-images.githubusercontent.com/15956627/168427511-b6719679-5c57-4415-a8a9-bad7bd0d9496.png)

This is not a bug. RSStT always drops those HTML tables with >= 2 columns since they are not able to be displayed well in Telegram messages or Telegram posts.

I am figuring out if there's a beautiful way to recognize these tables in which an image and its caption are separated into two columns., so that I can "fix" the "bug" soon with a proper render method.

Or just especially let tables with multiple columns but with a single row go, not dropping but rendering them into multiple rows?

**Comment by Rongronggg9** [comment]
Fixed in 8ef3fd0d48d304c69569f3b82143ce87cc529839.

Please note that the Docker image is currently [building](https://github.com/Rongronggg9/RSS-to-Telegram-Bot/runs/6435064251?check_suite_focus=true). It needs about 15 minutes before I can upgrade [@RSStT_Bot](https://t.me/RSStT_Bot).

**Comment by Rongronggg9** [comment]
A preview of the fix.

![](https://user-images.githubusercontent.com/15956627/168429858-54b97cdb-42b7-4750-b98e-9787c426c3fb.png)

**Comment by soredake** [comment]
Wow, now even with images, thanks!

**Comment by Rongronggg9** [comment]
OK, now [@RSStT_Bot](https://t.me/RSStT_Bot) is up-to-date.
